language: generic
sudo: required

services:
  - docker


before_install:
  - docker build -t pratheekcr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pratheekcr/docker-react npm run test


